name: CI Backend

on:
  push:
    paths:
      - 'ecommerce-backend/**'
  pull_request:
    paths:
      - 'ecommerce-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd ecommerce-backend
          ./mvnw clean install -DskipTests

      - name: Run tests
        run: |
          cd ecommerce-backend
          ./mvnw test
