-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT '9af1838023981a1e' HASH '2e993aff89f8d9dfd0c5cc924c59518218f54db71450c018e2a64e0219251a57' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."AUDIT_LOG"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 181) NOT NULL,
    "ACTION" CHARACTER VARYING(255),
    "ENTITY" CHARACTER VARYING(255),
    "ENTITY_ID" BIGINT,
    "TIMESTAMP" TIMESTAMP(6)
);   
ALTER TABLE "PUBLIC"."AUDIT_LOG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");    
-- 180 +/- SELECT COUNT(*) FROM PUBLIC.AUDIT_LOG;             
INSERT INTO "PUBLIC"."AUDIT_LOG" VALUES
(1, 'User 1 viewed product', 'Product', 1, TIMESTAMP '2025-07-10 18:49:39.30247'),
(2, 'User 1 viewed user', 'User', 1, TIMESTAMP '2025-07-10 18:49:42.562808'),
(3, 'User 1 viewed user', 'User', 1, TIMESTAMP '2025-07-10 18:50:02.022081'),
(4, 'User 1 viewed user 1', 'User', 1, TIMESTAMP '2025-07-10 20:02:00.799024'),
(5, 'User 1 viewed user 1', 'User', 1, TIMESTAMP '2025-07-10 20:02:06.032062'),
(6, 'User 1 viewed user 2', 'User', 2, TIMESTAMP '2025-07-10 20:02:13.926917'),
(7, 'User 1 viewed user 2', 'User', 2, TIMESTAMP '2025-07-10 20:03:38.577336'),
(8, 'User 1 listed active products', 'Product', NULL, TIMESTAMP '2025-07-10 20:34:49.474574'),
(9, 'User 1 searched products with query: Camiseta', 'Product', NULL, TIMESTAMP '2025-07-10 20:35:31.892517'),
(10, 'User 1 listed active products', 'Product', NULL, TIMESTAMP '2025-07-10 20:35:57.072417'),
(11, 'User 2 viewed user 3', 'User', 3, TIMESTAMP '2025-07-10 21:07:36.590152'),
(12, 'User 2 viewed user 3', 'User', 3, TIMESTAMP '2025-07-10 21:09:48.810544'),
(13, 'User 2 viewed user 3', 'User', 3, TIMESTAMP '2025-07-10 21:10:03.994394'),
(14, 'User 2 viewed user 3', 'User', 3, TIMESTAMP '2025-07-10 21:25:43.365723'),
(15, 'User 2 viewed user 3', 'User', 3, TIMESTAMP '2025-07-11 18:43:33.595024'),
(16, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:44:43.032141'),
(17, 'User 2 created product', 'Product', 7, TIMESTAMP '2025-07-11 18:45:18.425055'),
(18, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:45:18.435056'),
(19, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:49:22.660212'),
(20, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:49:45.644969'),
(21, 'User 2 updated product', 'Product', 1, TIMESTAMP '2025-07-11 18:49:51.97477'),
(22, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:49:51.98377'),
(23, 'User 2 updated product', 'Product', 1, TIMESTAMP '2025-07-11 18:49:55.735275'),
(24, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:49:55.744275'),
(25, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:50:09.816289'),
(26, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:50:46.84476'),
(27, 'User 2 created product', 'Product', 8, TIMESTAMP '2025-07-11 18:51:22.754805'),
(28, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:51:22.763805'),
(29, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:52:42.416165'),
(30, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:52:52.173701'),
(31, 'User 2 deleted product', 'Product', 8, TIMESTAMP '2025-07-11 18:52:58.236971'),
(32, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:52:58.244971'),
(33, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:53:14.629435'),
(34, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:53:17.959361'),
(35, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:53:24.300608'),
(36, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:53:35.202533'),
(37, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:53:46.84546'),
(38, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:53:50.864945'),
(39, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:54:19.063589'),
(40, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 18:54:19.066589'),
(41, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:54:20.591686'),
(42, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 18:54:20.591686'),
(43, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:56:47.041968'),
(44, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 18:56:47.043968'),
(45, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 18:57:33.393419'),
(46, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 18:57:33.396417');       
INSERT INTO "PUBLIC"."AUDIT_LOG" VALUES
(47, 'User 2 created inventory', 'Inventory', 6, TIMESTAMP '2025-07-11 18:57:49.265556'),
(48, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 18:57:49.273555'),
(49, 'User 2 deleted inventory', 'Inventory', 6, TIMESTAMP '2025-07-11 18:57:54.021655'),
(50, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 18:57:54.029656'),
(51, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 18:58:51.343818'),
(52, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:22:41.43853'),
(53, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:26:25.681873'),
(54, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:26:26.682712'),
(55, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:26:34.599554'),
(56, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:26:46.181056'),
(57, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:29:07.004465'),
(58, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:29:07.004465'),
(59, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:29:07.005465'),
(60, 'User 2 created order with items', 'Order', 5, TIMESTAMP '2025-07-11 19:31:36.591264'),
(61, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:31:36.600266'),
(62, 'User 2 created order with items', 'Order', 6, TIMESTAMP '2025-07-11 19:31:48.959386'),
(63, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:31:48.968388'),
(64, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:36:11.310745'),
(65, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:36:11.324745'),
(66, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:36:11.318745'),
(67, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:37:53.475379'),
(68, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:37:53.475379'),
(69, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:37:53.476381'),
(70, 'User 2 viewed order', 'Order', 5, TIMESTAMP '2025-07-11 19:37:56.074669'),
(71, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:39:22.853931'),
(72, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:39:22.853931'),
(73, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:39:22.854931'),
(74, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:39:28.725645'),
(75, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:39:28.725645'),
(76, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:39:28.725645'),
(77, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:39:30.336203'),
(78, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:39:30.336203'),
(79, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:39:30.336203'),
(80, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:39:31.575643'),
(81, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:39:31.576643'),
(82, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:39:31.576643'),
(83, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:39:32.758033'),
(84, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:39:32.758033'),
(85, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:39:32.758033'),
(86, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:40:40.515696'),
(87, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:40:40.516696'),
(88, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:40:40.517696'),
(89, 'User 2 viewed order', 'Order', 5, TIMESTAMP '2025-07-11 19:41:10.50672'),
(90, 'User 2 created order with items', 'Order', 7, TIMESTAMP '2025-07-11 19:41:22.767729'),
(91, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:41:22.776729');          
INSERT INTO "PUBLIC"."AUDIT_LOG" VALUES
(92, 'User 2 viewed order', 'Order', 7, TIMESTAMP '2025-07-11 19:41:27.055733'),
(93, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:41:49.439714'),
(94, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 19:41:49.439714'),
(95, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:41:55.776791'),
(96, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:46:13.610823'),
(97, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:46:38.392782'),
(98, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:47:05.512512'),
(99, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:47:08.099442'),
(100, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 19:47:08.101444'),
(101, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:47:10.093008'),
(102, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:47:10.094008'),
(103, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:47:10.094008'),
(104, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:47:11.187758'),
(105, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:47:24.681132'),
(106, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:48:30.058165'),
(107, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:48:31.27107'),
(108, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 19:48:31.27207'),
(109, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:48:32.842518'),
(110, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:48:38.339669'),
(111, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 19:48:41.141837'),
(112, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:48:41.141837'),
(113, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:48:46.023211'),
(114, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:48:46.023211'),
(115, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:48:46.024212'),
(116, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:48:47.554612'),
(117, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:51:00.230189'),
(118, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:51:07.88931'),
(119, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:51:07.88931'),
(120, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:51:07.88931'),
(121, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:51:09.241165'),
(122, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:51:12.888199'),
(123, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:51:12.888199'),
(124, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:51:12.888199'),
(125, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:51:13.906202'),
(126, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 19:51:34.076313'),
(127, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 19:51:35.172079'),
(128, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 19:51:35.172079'),
(129, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 19:51:35.173077'),
(130, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 20:01:23.52089'),
(131, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 20:01:25.58402'),
(132, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 20:01:25.584533'),
(133, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 20:01:25.584533'),
(134, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:01:38.970698'),
(135, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 20:01:38.971697'); 
INSERT INTO "PUBLIC"."AUDIT_LOG" VALUES
(136, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 20:01:40.057699'),
(137, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 20:01:40.0587'),
(138, 'User 2 listed all orders', 'Order', NULL, TIMESTAMP '2025-07-11 20:01:40.0587'),
(139, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:01:41.214381'),
(140, 'User 2 listed all users', 'User', NULL, TIMESTAMP '2025-07-11 20:01:43.538442'),
(141, 'User 2 listed active products', 'Product', NULL, TIMESTAMP '2025-07-11 20:01:45.387756'),
(142, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:01:46.949334'),
(143, 'User 2 listed all inventories', 'Inventory', NULL, TIMESTAMP '2025-07-11 20:01:46.949334'),
(144, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:02:01.618715'),
(145, 'User 2 searched products with query: c', 'Product', NULL, TIMESTAMP '2025-07-11 20:02:06.359959'),
(146, 'User 2 searched products with query: ca', 'Product', NULL, TIMESTAMP '2025-07-11 20:02:06.425799'),
(147, 'User 2 searched products with query: cam', 'Product', NULL, TIMESTAMP '2025-07-11 20:02:06.489731'),
(148, 'User 2 searched products with query: cami', 'Product', NULL, TIMESTAMP '2025-07-11 20:02:06.576414'),
(149, 'User 2 searched products with query: camis', 'Product', NULL, TIMESTAMP '2025-07-11 20:02:06.640417'),
(150, 'User 2 searched products with query: camise', 'Product', NULL, TIMESTAMP '2025-07-11 20:02:06.816778'),
(151, 'User 2 searched products with query: camiset', 'Product', NULL, TIMESTAMP '2025-07-11 20:02:06.922855'),
(152, 'User 2 searched products with query: camiseta', 'Product', NULL, TIMESTAMP '2025-07-11 20:02:07.00301'),
(153, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:02:07.754862'),
(154, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:04:51.82709'),
(155, 'User 2 searched products with query: t', 'Product', NULL, TIMESTAMP '2025-07-11 20:05:59.101486'),
(156, 'User 2 searched products with query: te', 'Product', NULL, TIMESTAMP '2025-07-11 20:05:59.522651'),
(157, 'User 2 searched products with query: ten', 'Product', NULL, TIMESTAMP '2025-07-11 20:05:59.714812'),
(158, 'User 2 searched products with query: teni', 'Product', NULL, TIMESTAMP '2025-07-11 20:05:59.784444'),
(159, 'User 2 searched products with query: tenis', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:00.090016'),
(160, 'User 2 searched products with query: teni', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:00.442043'),
(161, 'User 2 searched products with query: ten', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:00.662946'),
(162, 'User 2 searched products with query: te', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:01.009476'),
(163, 'User 2 searched products with query: t', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:01.513589'),
(164, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:01.704634'),
(165, 'User 2 searched products with query: g', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:02.338547'),
(166, 'User 2 searched products with query: gu', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:02.465631'),
(167, 'User 2 searched products with query: gua', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:02.642605'),
(168, 'User 2 searched products with query: guan', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:02.839612'),
(169, 'User 2 searched products with query: guant', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:03.153688'),
(170, 'User 2 searched products with query: guan', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:03.817635'),
(171, 'User 2 searched products with query: gua', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:04.089381'),
(172, 'User 2 searched products with query: gu', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:04.311761'),
(173, 'User 2 searched products with query: g', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:04.49744'),
(174, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:06:04.697643'),
(175, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:08:09.670931');       
INSERT INTO "PUBLIC"."AUDIT_LOG" VALUES
(176, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:19:10.640955'),
(177, U&'User 2 searched products with query: bal\00f3n and active: null', 'Product', NULL, TIMESTAMP '2025-07-11 20:19:18.434445'),
(178, U&'User 2 searched products with query: bal\00f3n and active: false', 'Product', NULL, TIMESTAMP '2025-07-11 20:19:21.130726'),
(179, U&'User 2 searched products with query: bal\00f3n and active: true', 'Product', NULL, TIMESTAMP '2025-07-11 20:19:22.29729'),
(180, 'User 2 listed all products', 'Product', NULL, TIMESTAMP '2025-07-11 20:19:23.015212');       
CREATE CACHED TABLE "PUBLIC"."INVENTORY"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 7) NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "PRODUCT_ID" BIGINT
);             
ALTER TABLE "PUBLIC"."INVENTORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");    
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.INVENTORY;               
INSERT INTO "PUBLIC"."INVENTORY" VALUES
(1, 50, 1),
(2, 30, 2),
(3, 80, 4),
(4, 40, 5),
(5, 25, 7);      
CREATE CACHED TABLE "PUBLIC"."ORDERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 8) NOT NULL,
    "DISCOUNT_APPLIED" FLOAT(53) NOT NULL,
    "ORDER_DATE" TIMESTAMP(6),
    "TOTAL_AMOUNT" FLOAT(53) NOT NULL,
    "USER_ID" BIGINT
); 
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");       
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;  
INSERT INTO "PUBLIC"."ORDERS" VALUES
(5, 20000.0, TIMESTAMP '2025-07-12 00:31:36.576', 380000.0, 3),
(6, 6000.0, TIMESTAMP '2025-07-12 00:31:48.949', 114000.0, 4),
(7, 19250.0, TIMESTAMP '2025-07-12 00:41:22.751', 15750.0, 3);         
CREATE CACHED TABLE "PUBLIC"."PRODUCT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 9) NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PRICE" FLOAT(53) NOT NULL
);           
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");      
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT; 
INSERT INTO "PUBLIC"."PRODUCT" VALUES
(1, TRUE, 'Camiseta deportiva', 'Camiseta', 35000.0),
(2, TRUE, 'Tenis running', 'Tenis', 120000.0),
(3, FALSE, U&'Bal\00f3n de f\00fatbol', U&'Bal\00f3n', 80000.0),
(4, TRUE, 'Gorra ajustable', 'Gorra', 20000.0),
(5, TRUE, 'Guantes de ciclismo', 'Guantes', 25000.0),
(6, TRUE, U&'Pantal\00f3n deportivo', U&'Pantal\00f3n', 60000.0),
(7, TRUE, U&'Protecci\00f3n UV ocular', 'Gafas de sol', 35000.0);  
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "FREQUENT_CLIENT" BOOLEAN NOT NULL,
    "PASSWORD" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255)
);               
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(2, 'admin@test.com', TRUE, '$2a$10$bjZfivRECpmQMxR23oiaFexx9l.CAoe4CvSDEsJd5mp7DEOZm3cce', 'admin'),
(3, 'juan@mail.com', TRUE, U&'$2a$10$bjZfivRECpmQMxR23oiaFexx9l.CAoe4CvSDEsJd5mp7DEOZm3cce\0009', 'juan'),
(4, 'ana@mail.com', TRUE, U&'$2a$10$bjZfivRECpmQMxR23oiaFexx9l.CAoe4CvSDEsJd5mp7DEOZm3cce\0009', 'ana'),
(5, 'luis@mail.com', FALSE, U&'$2a$10$bjZfivRECpmQMxR23oiaFexx9l.CAoe4CvSDEsJd5mp7DEOZm3cce\0009', 'luis'),
(6, 'maria@mail.com', TRUE, U&'$2a$10$bjZfivRECpmQMxR23oiaFexx9l.CAoe4CvSDEsJd5mp7DEOZm3cce\0009', 'maria'),
(7, 'pedro@mail.com', FALSE, U&'$2a$10$bjZfivRECpmQMxR23oiaFexx9l.CAoe4CvSDEsJd5mp7DEOZm3cce\0009', 'pedro');    
CREATE CACHED TABLE "PUBLIC"."ORDER_ITEMS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) NOT NULL,
    "PRICE" FLOAT(53) NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "ORDER_ID" BIGINT,
    "PRODUCT_ID" BIGINT
);  
ALTER TABLE "PUBLIC"."ORDER_ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2B" PRIMARY KEY("ID"); 
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_ITEMS;             
INSERT INTO "PUBLIC"."ORDER_ITEMS" VALUES
(1, 20000.0, 2, 5, 4),
(2, 120000.0, 3, 5, 2),
(3, 120000.0, 1, 6, 2),
(4, 35000.0, 1, 7, 1);   
ALTER TABLE "PUBLIC"."INVENTORY" ADD CONSTRAINT "PUBLIC"."UKCE3RBI3BFSTBVVYNE34C1DVYV" UNIQUE("PRODUCT_ID");  
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FK32QL8UBNTJ5UH44PH9659TIIH" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."ORDER_ITEMS" ADD CONSTRAINT "PUBLIC"."FKBIOXGBV59VETRXE0EJFUBEP1W" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."ORDERS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."INVENTORY" ADD CONSTRAINT "PUBLIC"."FKP7GJ4L80FX8V0UAP3B2CRJWP5" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."ORDER_ITEMS" ADD CONSTRAINT "PUBLIC"."FKLF6F9Q956MT144WIV6P1YKO16" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;               
